heat_template_version: 2014-10-16

parameters:
  name:
    type: string
    default: lbserver
  syseleven_net:
    type: string
  public_network_id:
    type: string
    default: 4c23774c-395b-49d0-b8e1-347e886fa9bf 

resources:
  allow_ssh:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming traffic from anywhere.
      name: allow incoming traffic, tcp
      rules: 
        - {direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 22, port_range_max: 22, protocol: tcp}
        - direction: ingress
          protocol: icmp

  allow_webtraffic:
    type: OS::Neutron::SecurityGroup
    properties:
      description: allow incoming web traffic from anywhere.
      name: allow incoming web traffic
      rules: [{direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 80, port_range_max: 80, protocol: tcp}, {direction: ingress, remote_ip_prefix: 0.0.0.0/0, port_range_min: 443, port_range_max: 443, protocol: tcp} ]

  syseleven_lbserver:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      user_data_format: RAW
      user_data: { get_resource: cloud-init-config }    
      image: Ubuntu-14.04-LTS from cloud-images.ubuntu.com
      flavor: m1.micro
      networks:
        - port: { get_resource: syseleven_port }


  cloud-init-config:
   # cloud init demo resource
   type: OS::Heat::CloudConfig
   properties:
     cloud_config:
       runcmd:
         - /root/install_lb.sh
       write_files:
         -  content: { get_file: scripts/install_lb.sh }
            permissions: 0755
            path: /root/install_lb.sh
         -  content: { get_file: config/avahi-http.service }
            permissions: 0644
            path: /etc/avahi/services/avahi-http.service
         -  content: { get_file: scripts/update_sessionconfig }
            permissions: 0700
            path: /usr/local/sbin/update_sessionconfig
       users:
           - name: syseleven
             gecos:  Workshop user
             lock-passwd: false
             sudo: ALL=(ALL) NOPASSWD:ALL
             shell: /bin/bash
             ssh-authorized-keys:
               - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBHhKPUBIv4EhNIDrXYsoBPNTCzMXtIkCcqEiXjx1AH8WNRHYN7blzV+qv9SJOzfi9OcfQ3o+qR2YwYT+z2464crW9xZHrtEerVDWMeCs3ZsnGxiFM40xpKhWHuTZNv+Y+07t8CHAdfGlSM3st2NrdwB2qWBTvoXTuhc9/4UeEM5rsLFDFIb84P4VXiMLooo8ovDWZ4I1A1+cmbiG9PDPIXn2I3LLvXfSn7rbTal5dJixZAfue1sKCwoFxzEIjdD2MRfkkwcYRbm2wyU2Gf3XTE4OOl/AIoCvgnp2+zFH6rdVme+lsX32ddS2dayoU50VpMz1jWq+fR5bnGyvYnJux janpeschke@ws171.sys11.net'
               - 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvfTxEm59MSzCoZgSd/gkD+MCxxgsCrlkvq/37mwzW65YrEggWM7MArISaJGzj8iqpR53B524Z72pc0nkrlv6tb4ECHEDsTHuYVjCr70wBreyGBVlLswMKHPL/mXmaUvis/rJvbHJtTJZpehJteMIiwwJEBqhch6Jj6suQaSeT11QJrIvFpF5ddphopwqe90VCby0RyIbi0MISjWILcsEUvLMgPHTOXFFS5NPs6hKiNPC9gl7BZizMf1bZvizlwZ7SKVSPttB6ZTMiea9WauPcMYH7zYjdHOLvWVgpoefp/0o01uCzQSsBBiX1+SRZLe9uxrrrsg8xlvaD/aIBN9Avw== norbertauler@ws159.sys11.net'
               - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBHhKPUBIv4EhNIDrXYsoBPNTCzMXtIkCcqEiXjx1AH8WNRHYN7blzV+qv9SJOzfi9OcfQ3o+qR2YwYT+z2464crW9xZHrtEerVDWMeCs3ZsnGxiFM40xpKhWHuTZNv+Y+07t8CHAdfGlSM3st2NrdwB2qWBTvoXTuhc9/4UeEM5rsLFDFIb84P4VXiMLooo8ovDWZ4I1A1+cmbiG9PDPIXn2I3LLvXfSn7rbTal5dJixZAfue1sKCwoFxzEIjdD2MRfkkwcYRbm2wyU2Gf3XTE4OOl/AIoCvgnp2+zFH6rdVme+lsX32ddS2dayoU50VpMz1jWq+fR5bnGyvYnJux janpeschke@ws171.sys11.net'
               - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmz4l7MtNlz7G+Sdmbmed79XgvPsS3tC5yk11yCpQ6zjVxcDeYzWhiLTAUHHRlc9Tprgjyzsexi6h+2gr/uHIsEOw5bOlVBRb6YshKIK8NuTtMs1ltFuZCp4XnibJv1o0mNiuRXHPxUHnDr0LvLkJh++qO1BuQC5rzD/NlbL+kvECiVFL5n/vfWFHvNbgIbtggH9cjjsftjylWnhSjkMCmLCCBJeSALHQUAOM8xiRvXYj8omAFqfc7T+HJQHGcmIs3itEBF96toqta6C2/2J9f6zW9G3P/kEz6Zagfe0wxXrb5lXzyBEFGd8Xgx1BKhz2qKAQN4cXFOKjtH1V0LlwV matthias.gronwald@votum.de'
               - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDG/KeVodk+qKQtTYrCWxSqVyISDwAZZBDdWANcEU5KuXFb2c1jrhFURReDE/WxQJ8Sd5Dt12rmi5L1dELHdGrQ/lJTp0AJpf0dgOhhOAbCjfsTLlKa5C8b03vECTvmjVQNujdca+JWaq3B0xzLs7JSA86T3NHp8oXo6ikAZP6ZzN19X3BlYlLAGn2UupPx1/ACEqfgZ59px9l2hO7uRW7x3ELTT+UX9SGeMtsNC8Q5mPDM06+3uzN673w1fVUyIf25DrejpkhYj2Mvs1zYoLqDi2qCflVEmdMxkHFuYNAB1aqhLuNO5pltLuMAS7y63AYFBa2MpM2mvOATVF84ZEZvCi3X1tksHU3binZwrEq8caujsqbXwb2EhIN4G8pSl+rgX32vAkC3okH8UmHo+/s4VpguzgEeA1rGa3NHUMcjk5fpX8lM08b2clrwfCXEMU/z8g88aYR0TpYk+IjR3cFPrfgCeMs9gyp7kMOFJ3pk5y8Xf8ZoHpCykkk3jYVfVoUBo9xVuEa03X6HelyOWdwMUdGzwDej+p5G8o/UOgXm4sqEMNXIqsNGkblJeu4u8vIc98VtPiirvsJEAiA4cHmoQXFeS/cVwZtaFOxH0RJZYkzIU2qHVCwke5Md0YS1ZCDES8VDMOxGTm5arkGju8oZzDbcLBeAz8crAFxAy5mi8w== kschikarski@cadmins-MacBook-Pro'
               - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/xTIuB5qVY4NrsdpC6mWMtlE6R9ZJb2YuN4OJXId8EBMKyWx0VwndB9JgwXdLnmjrxAOe78A2Hl7j6iD++QOIQas6SLUj7cp5M4I2y5aS5sgVz/jeqoCSgC4oG8kQyUGfWMlKXsqGOdq6pv5P6DDTkbuqkxxlx5N3PplalvCE9X2l9Mq23bZlplrHi/1slQfJi0F9cAMJjAjDAnajEAiajsSk63N5ZawxJmX9u4wvHwjqPI21xnbstjod8N1GaaTJrx7XkB1EGLi63SMNDsGS6SqN51blijEdBGsxHzFOD2doE7quuGaGSjCpveAb1AHqUMSnJNbHSjWZqMRvg+lHd0sJFt/oPaZvi6fNmrytr0Fvdq8Lytlquo7L189kgfw3xH5TmtC7/EHiFDdBFKVyrbOEQewHvgh14zJkiSvW8/F9ZSLNoJ5fiJAD3UokzWGg+8CDG7HVBMMWDVWUNyKRwJL+aLCuN4w7oO89TjBAd9dOQ/rZ8C4LaZo+UpiFxdHqS7XubZllwQFlXHp3vjXitQtdL8UZCmOH7JOUil8XDv0ojV1yEv/Q3D41YqIOEyon+el01NLaUFgtiZJUXjT8+PBRn82drSwws5tM4iKxPFBQycJyqf1YhLX3gH2L5qEljzvQyKYsrFmGRU3Xpje8jq4dlj3ljBZVFsiTGayG/w== thomas.kuehnel@spryker.com'
               - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCoCBOfncGlebENcKi7fKVG+S1v2lDIprA72kd/E3eKQRHbXfQBpgBxOlG6YdhvkA1QARDFMDw/mKypM7ayaRcQ19L9+tmpXgmwHakwmTKjllp+5Y9kj4pW2zACppvQk/46EoN0ebERg4F6xnCa909GeiCOUaAsYID7qwduKrMwVhlUZxQSmJ4iJQ30pxEWJwEHzZTSoOE6zQ/3qvyYKttq4hsHz5aR8BMwEJ++wo4urrbzBwtxYc3wuLyCkg+jFieU5bQJSgKdb24PJCuQIBmducT44BuDRxzDDvKX9Yv19K/Xc/1w/rLHvcU8AHnALDucIaPRx7QCqw9/vnyKjiwp sergej.braznikov@symmetrics.de'
               - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDczm4Guot89T4IYeY/gG0TcU2XRyb6xHFPaj7mlKXH190bc65tpD6GiOlsd8MPOyWNBfw/7EU0Z5CY0L0PiBU/5eT+WcaXrs+nie89Ixl9t5aRPj6cIDxLf4n00dSGlFasRwJjkZs9SMWkbC8o2rxoWhr2Cx7QorNWrxfcgYpgtzERCJs75MLQaATQcs7sdUPbplMt9GXMYlS0N5Fwa0PLRzYepmcT7I/8mYaaJmzs1u8ZcyFlktej1q0jc8SCICQA8RafpFD54ivJvmyLxcEUisCaclVUaW5fPLtZg8XFQKPrahLquu6SuS38mYTZOB/8jsRO/d8iCG5m+BhyN4Mr raymond.schmidt@votum.de'

  syseleven_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: syseleven_net}
      security_groups: [ {get_resource: allow_ssh}, {get_resource: allow_webtraffic}, default ]

  syseleven_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network_id }
      port_id: { get_resource: syseleven_port }

outputs:
  lb_ip:
    description: loadbalancer floating ip
    value: { get_resource: syseleven_floating_ip }
